### ISSUE TITLE
Exchange Vertcoin Link

### ISSUE THREAD

**Issue by rogerabm** [vertcoin-project/vertcoin-website#10]
In the section labeled Your Money, Your Bank, Your Control. There is a link to **Exchange Vertcoin**, which points to https://new.vertcoin.org/purchase/ when it should actually be pointing to https://new.vertcoin.org/trading/

**Comment by metalicjames** [comment]
Related to this https://github.com/vertcoin-project/vertcoin-website/issues/12. Fixed in https://github.com/vertcoin-project/vertcoin-website/issues/15
