### ISSUE TITLE
Links targets

### ISSUE THREAD

**Issue by rogerabm** [vertcoin-project/vertcoin-website#11]
Section: How?
Why Vertcoin is Proof-Of-Work **should not** open in _blank

Section: Fair To Mine, Forever
Specialized hardware link **should** open in _blank

Section: Feel Free To Chat!
Discord and reddit links **should** open in _blank

All links under Trading page **should** open in _blank

**Comment by metalicjames** [comment]
Fixed in https://github.com/vertcoin-project/vertcoin-website/pull/15
