### ISSUE TITLE
Team photos

### ISSUE THREAD

**Issue by tvector** [vertcoin-project/vertcoin-website#27]
I would suggest you get some professional photos of the team and get definitely get a new photo of Alex Turek.  If you are asking people to invest, I think it should look like a serious project.

**Comment by CryptoPlankton** [comment]
We never ask people to invest. Vertcoin is not an investment, its a money transfer network.

Agree, updating the picture.

**Comment by tvector** [comment]
Call it what you want.  It's just semantics, but if people are buying VTC off of an exchange and not using it, it's an investment.
