### ISSUE TITLE
Grammar/Spelling errors

### ISSUE THREAD

**Issue by Tucker178** [vertcoin-project/vertcoin-website#3]
**On the homepage:** 
"Commited To Building A Balanced System"
"Commited" should be "Committed."

**On the Accept Vertcoin page:** 
"Vertcoin is compatible with most exiting libraries intended for Bitcoin..."
I'm assuming "exiting" should be "existing."

**On the Specs Explained page:** 
- The sections are all questions - some have question marks and some do not. All of the section titles should be consistent in my opinion (either all have question marks or all question marks omitted).
- "It comprises of an extremely difficult computation..."
I believe "It comprises of" should be "It comprises an extremely..." or "It is comprised of."

**Comment by burley01** [comment]
**On Why Is The Block-Time 2.5 Minutes**   
The phrase "sweet spots" is used, then later "sweetspot" (no space) is used near the end of the paragraph.  Recommend to change one to maintain consistency.

**Comment by LilliputianVapor** [comment]
**On The Community Tab**
"We are constly looking for more people to help out and build Vertcoin."
In this sentence, "constly" should be spelled "constantly".
