### ISSUE TITLE
trembing of the twitter icon

### ISSUE THREAD

**Issue by exenal** [vertcoin-project/vertcoin-website#38]
There is a trembing of the TWITTER icon (on the top right corner) when a cursor positioning/repositioning over the reddit icon

**Comment by masterix65** [comment]
bug reproduced on chrome, it doesn't seem to happen on firefox

**Comment by CryptoPlankton** [comment]
Can't reproduce this bug on chrome

**Comment by exenal** [comment]
Video

[2018-03-27_9-54-14.zip](https://github.com/vertcoin-project/vertcoin-website/files/1850012/2018-03-27_9-54-14.zip)
