### ISSUE TITLE
How's Vertcoin ASIC resistance ?

### ISSUE THREAD

**Issue by iamhuk** [vertcoin-project/vertcoin-website#5]
The website does NOT explain clearly how Vertcoin is ASIC resistance. 

Vertcoin has been forked to fight ASIC before, plus the commitment of the team to fork again if there is ASIC. I think these 2 important points need to be added to the website.

**Comment by metalicjames** [comment]
Here is a partial fix: https://github.com/vertcoin-project/vertcoin-website/pull/9

It should probably be written more about on the content pages, too.

**Comment by iamhuk** [comment]
@metalicjames , @CryptoPlankton 
I saw this was fixed, but then someone removed it? 
The current website says "Vertcoin remains resistant to the specialised hardware" but not mention HOW ?
