### ISSUE TITLE
Promote the "Vertcoin community" on the team page.

### ISSUE THREAD

**Issue by potatohodler** [vertcoin-project/vertcoin-website#67]
The team page is very team member-centric, which gives the impression that a select few Vertcoin team member's are more important than the community.

Although personally I would be in favour of having no distinction between the team and the community at all on the web-site (i.e. there is only one community) it would be great if we could at a minimum promote the "Vertcoin Community" item on the team page to the first position in the team to succinctly express the importance of the Vertcoin community.

**Comment by CryptoPlankton** [comment]
Changed the ordering so community is first in the list
